api_platform:
  title: 'Théo Fief Test API'
  description: 'Théo Fief Test API Data Interface'
  version: 1.0.1
  mapping:
    paths: [ '%kernel.project_dir%/src/Entity' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    api_keys:
      apiKey:
        name: Authorization
        type: header
  formats:
    jsonld: [ 'application/ld+json' ]
    jsonhal: [ 'application/hal+json' ]
    jsonapi: [ 'application/vnd.api+json' ]
    json: [ 'application/json' ]
    xml: [ 'application/xml', 'text/xml' ]
    yaml: [ 'application/x-yaml' ]
    csv: [ 'text/csv' ]
    html: [ 'text/html' ]
    myformat: [ 'application/vnd.myformat' ]
  docs_formats:
    jsonld: [ 'application/ld+json' ]
    jsonopenapi: [ 'application/vnd.openapi+json' ]
    html: [ 'text/html' ]
  serializer:
    hydra_prefix: true
  defaults:
    pagination_enabled: false
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true

#   event_listeners_backward_compatibility_layer: false
#   keep_legacy_inflector: false
