framework:
    notifier:
        chatter_transports:
            mattermost: '%env(MATTERMOST_DSN)%'
            fakechat+email: '%env(FAKE_CHAT_DSN)%'
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
